### ISSUE TITLE
Tweak the code style to match the GDScript style guide

### ISSUE THREAD

**Issue by Calinou** [quentincaffeino/godot-console#25]
Right now, this plugin uses camelCase for method names, whereas snake_case is typically used in GDScript. Constants also use PascalCase, but the [GDScript style guide](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) recommends using UPPER_SNAKE_CASE for those.

It would be good to modify scripts to better match the core Godot API and other established plugins out there. This way, users can use the plugin's methods without introducing style clashes in their existing scripts.

**Comment by quentincaffeino** [comment]
On the second though, this is too much work and It would break any current code that uses this package.

I'm fine with rewriting this if I could know somehow this won't affect many people. That's why I don't just remove old api but try to gently move user to new ones.

Constants are in upper snake case where they are constants. Probably you are talking about first few lines in `Console.gd`, those are not constants, but rather static final class properties, and I tried to point that with pascal case. Sadly there's no way to do that natively with godot language features.

**Comment by gxhamster** [comment]
We could do in stages instead of just changing in one go

**Comment by quentincaffeino** [comment]
Internal stuff could be rewritten in one go.
With public apis, I would prefer doing it by deprecating old methods, alerting users about that, and adding new ones so users are able to migrate.

**Comment by gxhamster** [comment]
I am going to try doing that then if thats okay

**Comment by quentincaffeino** [comment]
I've began the migration with commit #9b5435. Now every one is able to migrate till the next version, then old methods will be removed. I will update docs later today.

**Comment by quentincaffeino** [comment]
I've updated the docs in #792aa07.

I may have missed something, in case of that, you know what to do.

This will be in the next version.
