### ISSUE TITLE
Somewhat new to the engine, either I'm doing something wrong or the update has broke it.

### ISSUE THREAD

**Issue by VitexHD** [QuentinCaffeino/godot-console#5]
![image](https://user-images.githubusercontent.com/31520916/55040068-ccfec380-501e-11e9-8d3c-a4ba60823424.png)

Not sure why, would appreciate some help <3
Folder Layout:
Programming->"GoDot Engine"->"Mini Platform Game"->(Crap and then)src/(all the source files for this project)

**Comment by QuentinCaffeino** [comment]
Hello, could you please tell me what godo version are you using?
Best

**Comment by VitexHD** [comment]
Thanks for the reply, I am using GoDot 3.1 (Steam).

**Comment by QuentinCaffeino** [comment]
I can fix most of the issues, but there is one I cannot fix. Creating class factories inside classes static methods doesn't work anymore. I'll write a n issue when I'll have more time.

**Comment by QuentinCaffeino** [comment]
Waiting for response:
https://github.com/godotengine/godot/issues/27491

**Comment by jahd2602** [comment]
@VitexHD have you defined `UNKNOWN` somewhere?

**Comment by QuentinCaffeino** [comment]
@jahd2602 that isn't because of him. That is because of godot changed how it works with enums in 3.1
![image](https://user-images.githubusercontent.com/2855777/55163807-c2514500-516a-11e9-8d50-59e1105f3863.png)
_https://github.com/godotengine/godot/blob/3.1-stable/CHANGELOG.md_

Soon I'll push a fix for that, but there's still a real problem with new method.

**Comment by jahd2602** [comment]
Ok then. We can close this issue then.

**Comment by VitexHD** [comment]
Ok, thanks for the help. Really appreciate it :)
