### ISSUE TITLE
Request to change default key to open console

### ISSUE THREAD

**Issue by SpyrexDE** [quentincaffeino/godot-console#66]
So the problem with just the key code KEY_QUOTELEFT is that on some keyboards it refers to a not that rare used letter. That's also the reason why VSCode's default key to open the console is Ctrl + KEY_QUOTELEFT.
I would ask for doing the same here, so people with a different keyboard layout won't be forced to adjust the settings.

**Comment by quentincaffeino** [comment]
Initially one of my inspirations was source engine console. But yeah, I agree, this would be much better.

**Comment by quentincaffeino** [comment]
I've published a new version https://github.com/quentincaffeino/godot-console/releases/tag/v3.3.0, it will take some time to publish on godot assets website. Also this will affect only new installations because I don't want to mess with peoples settings if they have changed them. To change it yourself you can go to `project > project settings > input map`, search for `quentincaffeino_console_toggle` and change it there.
